### ISSUE TITLE
Not an issue, just thanks!

### ISSUE THREAD

**Issue by CorradoBarbero** [soheilkd/SingleInstanceCore#1]
Thanks mate, this works like a charm.

Just a small typo, change:
bool isFirstInstance = SingleInstance<App>.InitializeAsFirstInstance("soheilkd_EPlayerIPC"))
to:
bool isFirstInstance = SingleInstance<App>.InitializeAsFirstInstance("soheilkd_EPlayerIPC");
in the README (change the ) to a ;)

**Comment by soheilkd** [comment]
Fixed. Thanks
