### ISSUE TITLE
Is not this library the same as...?

### ISSUE THREAD

**Issue by Tum4ik** [soheilkd/SingleInstanceCore#10]
I used this code some years ago:
```csharp
var processesCount = Process.GetProcesses().Count(p => p.ProcessName == Process.GetCurrentProcess().ProcessName);
if (processesCount > 1)
{
  Shutdown();
}
```
Does not it do the same as this library in general?

**Comment by soheilkd** [comment]
You can do that as you prefer. This library also gets arguments from secondary instances. My intent was to let only one instance to run and handle files that the user wants to open. With this library you can decide what to do when there is an instance running, shutdown or continue running with a warning. 
As for checking running processes, Mutex provides a more reliable way to know whether an instance is already running.
