### ISSUE TITLE
.NET 5 compatibility

### ISSUE THREAD

**Issue by nikeee** [soheilkd/SingleInstanceCore#3]
Does this library also work with .NET 5/6?

Is it possible to use it with WinForms?

**Comment by soheilkd** [comment]
Though it's built on .NET Core 3 and should work on .NET 5, it is for WPF only now. 

I may make it compatible with WinForms once I find workarounds where WPF library is used.

**Comment by soheilkd** [comment]
You can now use it with WinForms. Check new readme and make sure you have version 2.0.0
