### ISSUE TITLE
WinForms Usage

### ISSUE THREAD

**Issue by nikeee** [soheilkd/SingleInstanceCore#7]
Awesome library!

I'm trying to get it to work with WinForms.

This is my current attempt:
```csharp
static class Program
{
    [STAThread]
    static void Main(string[] args)
    {
        var app = new TestApplication();

        var isFirstInstance = app.InitializeAsFirstInstance("Test");
        if (isFirstInstance)
        {
            try
            {
                app.Run();
            }
            finally
            {
                SingleInstance.Cleanup();
            }
        }
    }
}

class TestApplication : ISingleInstance
{
    public void Run()
    {
        Application.SetHighDpiMode(HighDpiMode.SystemAware);
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);
        Application.Run(new MainForm());
    }

    public void OnInstanceInvoked(string[] args)
    {
        MessageBox.Show("OnInstanceInvoked");
        throw new NotImplementedException();
    }
}
```
Observation:
- There is only one instance created
- `OnInstanceInvoked` is not invoked on any instance
- `Application.Run(new MainForm())` blocks until the main form is closed
- In the second instance, `InitializeAsFirstInstance` returns `false`, as expected

What am I doing wrong?

If we get this to work, I'd like create a PR to put a WinForms sample in the README.

**Comment by nikeee** [comment]
Well, I don't know what the problem was, but it now works with the above code. Want me to add this sample to the README?

**Comment by soheilkd** [comment]
I wish I could reproduce what happened in your first attempt, to find out the subtle bug. But it worked fine.

Yeah sure you can add that to README as a WinForms sample

**Comment by nikeee** [comment]
Done in #8
